package agent.user_interface_layer;

import javax.swing.JTabbedPane;

/**
 *
 * @author arsalan
 */
public class ManageSales extends javax.swing.JPanel {

    private final Sales viewSales = new Sales();
    private final PerformSale performSale = new PerformSale();

    /**
     * Creates new form Customer
     */
    public ManageSales() {
        initComponents();
        salesTabBar.add(performSale, "Sold Property");
        salesTabBar.add(viewSales, "View All Sales");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salesTabBar = new javax.swing.JTabbedPane();

        salesTabBar.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        salesTabBar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                salesTabBarStateChanged(evt);
            }
        });
        salesTabBar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                salesTabBarPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(salesTabBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(salesTabBar, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salesTabBarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_salesTabBarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_salesTabBarPropertyChange

    private void salesTabBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_salesTabBarStateChanged
        // TODO add your handling code here:

        JTabbedPane sourceTabbedPane = (JTabbedPane) evt.getSource();
        int index = sourceTabbedPane.getSelectedIndex();
        switch (index) {
            case 0:
                performSale.fillAllDropDown();
                break;
            case 1:
                viewSales.updateTable();
                break;
        }
    }//GEN-LAST:event_salesTabBarStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane salesTabBar;
    // End of variables declaration//GEN-END:variables

}
