package agent.user_interface_layer;

import agent.business_logic_layer.DataManager;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arsalan
 */
public class Sales extends javax.swing.JPanel {

    /**
     * Creates new form Sales
     */
    public Sales() {
        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();

        jPanel10.setLayout(null);

        btnRefresh.setText("Refresh");
        btnRefresh.setToolTipText("Refresh Page");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel10.add(btnRefresh);
        btnRefresh.setBounds(280, 440, 190, 40);

        btnExport.setText("Export to Excel");
        btnExport.setToolTipText("Save Data to Excel ");
        btnExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        jPanel10.add(btnExport);
        btnExport.setBounds(500, 440, 220, 40);

        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Customer Name", "Selling Price", "Commision"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblSales);

        jPanel10.add(jScrollPane7);
        jScrollPane7.setBounds(10, 20, 980, 410);

        btnClear.setText("Clear");
        btnClear.setToolTipText("Clear Screen");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel10.add(btnClear);
        btnClear.setBounds(880, 440, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1105, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        updateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        DataManager.getInstance().exportDataToExcel(tblSales, "Sales");
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        DefaultTableModel aModel = (DefaultTableModel) tblSales.getModel();
        aModel.setRowCount(0);
        tblSales.setModel(aModel);
    }//GEN-LAST:event_btnClearActionPerformed

    public void updateTable() {
        ArrayList<ArrayList> list = DataManager.getInstance().getPropertyManager().getSales();
        String[] tableColumnsName = {"Date", "Customer Name", "Selling Price", "Comission"};
        DefaultTableModel aModel = (DefaultTableModel) tblSales.getModel();
        aModel.setRowCount(0);
        aModel.setColumnIdentifiers(tableColumnsName);

        for (int i = 0; i < list.size(); i++) {
            ArrayList innerList = list.get(i);
            Object[] objects = new Object[4];
            objects[0] = innerList.get(0);
            objects[1] = innerList.get(1);
            objects[2] = innerList.get(2);
            objects[3] = innerList.get(3);
            aModel.addRow(objects);
        }
        tblSales.setModel(aModel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tblSales;
    // End of variables declaration//GEN-END:variables
}
